name: "deploy"

on:
  # アクションを手動実行する場合必要
  workflow_dispatch:

  schedule:
    # cacheが消えないよう定期的に実行する
    - cron: "0 0 */6 * *"

  push:
    branches:
      - "master"

jobs:
  deployment:
    name: "deployment"
    runs-on: "ubuntu-latest"
    steps:

      # https://github.com/actions/checkout
      - name: "checkout master"
        uses: "actions/checkout@v4"
        with:
          ref: "master"

      # https://github.com/actions/cache
      - name: "cache ~/.stack, .stack-work"
        uses: "actions/cache@v3"
        with:
          path: |
            ~/.stack
            .stack-work
          key: "stack-${{ hashFiles('stack.yaml', 'package.yaml') }}"
          restore-keys: "stack-"

      - name: "build site"
        run: "stack build && stack exec site build"

      # https://github.com/peaceiris/actions-gh-pages
      - name: "deploy"
        uses: "peaceiris/actions-gh-pages@v3"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_dir: "./_site"
          publish_branch: "build"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
